// <auto-generated />
namespace SoldiersInfo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changing_Annoucement_Fix_Grammar_Error : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changing_Annoucement_Fix_Grammar_Error));
        
        string IMigrationMetadata.Id
        {
            get { return "201605040516544_Changing_Annoucement_Fix_Grammar_Error"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
